baseURL = "/"
languageCode = "en-us"
title = "David Eisenmenger"
theme = "hugo-lodi-theme"
googleAnalytics = "UA-138889713-1"

[params]
    theme_color = "#2F468A"
    description = "User Experience Design Portfolio"
    description_photo = "PortfolioMockup.png"
    favicon = "ELogo.svg"
    logo = "Elogo.svg"
    email = "david@eisenmenger.co"
    #facebook = "david.eisenmenger.9"
    twitter = "deeisenmenger"
    #dribbble = ""
    linkedin = "https://www.linkedin.com/in/d-eisen/"
    #medium = ""

[params.nav]
    enable = true

[params.hero]
    enable = true
    avatar = "HeadshotFinal.jpg"
    subtitle = "I am David, a User Experience Designer and Researcher"
    # subtitle2 = "Empathy Specialist"
    hero_right = ["A user experience designer and researcher with a background in program development and healthcare management.",

    "My mission is to add value to others. I am passionate about improving services that support other people. My approach uses human centered design in eliciting user needs and goals, working creatively and collaboratively toward solutions.",
    ]
    
    # resume = "Resume_Eisenmenger.pdf"

[params.process]
    enable = true
    title = "My Process"
    # subtitle = "Full Process Design"

[params.case_studies]
    enable = true
    title = "Case Studies"
    # subtitle = "User Experience Design"

[params.footer]
    enable = true
theme = "hugo-lodi-theme"
