baseURL = "/"
languageCode = "en-us"
title = "David Eisenmenger"
theme = "hugo-lodi-theme"
googleAnalytics = "UA-138889713-1"

[params]
    theme_color = "#4ca2ff"
    description = "David Eisenmenger, UX Design Portfolio"
    description_photo = "portfolio.png"
    favicon = "logo.png"
    logo = "logo.png"
    email = "david@heronblue.design"
    facebook = "david.eisenmenger.9"
    twitter = "deeisenmenger"
    #dribbble = ""
    linkedin = "https://www.linkedin.com/in/d-eisen/"
    #medium = ""

[params.nav]
    enable = true

[params.hero]
    enable = true
    avatar = "HeadshotFinal.jpg"
    subtitle = "Hello! I'm David, a User Experience Designer and Researcher"
    # subtitle2 = "Empathy Specialist"
    hero_right = ["**A user experience designer and researcher with a diverse background in product design and healthcare management.**",
    
    "My mission is to add value to others. My focus is to solve problems with solutions that create a seamless user experience, make people happy, and add value to the process. My approach uses human centered design in eliciting user needs and goals, working creatively and collaboratively toward solutions.",
    
   "I have spent my career helping other people to do what they do--better. Trained as a psychotherapist I have developed a deep ability to listen, be empathetci, and help people find real world solutions to their problems.",
    
    "As a chaplain and a healthcare manager I designed new programs for teams and offered support to individuals to help better their lives.",
    
    "As a corporate director, I designed leadership development programs to help hundreds including corporate leaders, professionals, and patients served by an Inc. 2000 healthcare organization.",

    "Now as a user experience designer I make sure that that adding value to the end user remains at the center of what I do."
    ]
    
    resume = "Resume_Eisenmenger.pdf"

[params.process]
    enable = true
    title = "My Process"
    # subtitle = "Full Process Design"

[params.case_studies]
    enable = true
    title = "Case Studies"
    subtitle = "User Experience Design"

[params.footer]
    enable = true
theme = "hugo-lodi-theme"
