baseURL = "/"
languageCode = "en-us"
title = "David Eisenmenger"
theme = "hugo-lodi-theme"
googleAnalytics = "UA-138889713-1"

[params]
    theme_color = "#4ca2ff"
    description = "David Eisenmenger, UX Design Portfolio"
    description_photo = "portfolio.png"
    favicon = "logo.png"
    logo = "logo.png"
    email = "david@heronblue.design"
    facebook = "david.eisenmenger.9"
    twitter = "deeisenmenger"
    #dribbble = ""
    linkedin = "https://www.linkedin.com/in/d-eisen/"
    #medium = ""

[params.nav]
    enable = true

[params.hero]
    enable = true
    avatar = "HeadshotFinal.jpg"
    subtitle = "Hello! I'm David, a User Experience Researcher and Designer"
    # subtitle2 = "Empathy Specialist"
    hero_right = ["**A user experience researcher and designer with a diverse background in product design, social work, and healthcare management. My focus is to solve problems with solutions that create a seamless user experience, make people happy, and add value to the product. My approach uses human centered design in eliciting user needs and goals working creatively and collaboratively toward solutions.**"]
    
    resume = "Resume_Eisenmenger.pdf"

[params.process]
    enable = true
    title = "My Process"
    # subtitle = "Full Process Design"

[params.case_studies]
    enable = true
    title = "Case Studies"
    subtitle = "User Experience Design"

[params.footer]
    enable = true
theme = "hugo-lodi-theme"
