baseURL = "/"
languageCode = "en-us"
title = "David Eisenmenger"
theme = "hugo-lodi-theme"
googleAnalytics = "UA-XXXXXXXX-Y"

[params]
    theme_color = "#4ca2ff"
    description = "Portfolio of David Eisenmenger, UX Designer"
    description_photo = "portfolio.jpg"
    favicon = "logo.png"
    logo = "logo.png"
    email = "david@heronblue.design"
    facebook = "david.eisenmenger.9"
    twitter = "deeisenmenger"
    #dribbble = "alexiscollado"
    linkedin = "https://www.linkedin.com/in/d-eisen/"
    #medium = "ahvccollado"

[params.nav]
    enable = true

[params.hero]
    enable = true
    avatar = "HeadshotFinalBW.jpg"
    subtitle = "Hello, I'm David, a UX Designer & Empathy Specialist"
    # subtitle2 = "Empathy Specialist"
    hero_right = ["**A user experience designer with a diverse background in healthcare, social work, and nonprofit managment. My focus is to help create seamless user experiences that work well, make people happy, and add value to the product. I have an extensive history focused on wellbeing in the user's experience. My approach uses human centered design in eliciting user needs and goals working creatively and collaboratively toward solutions.**", 
    #"I founded [User Experience Society](https://www.facebook.com/UXSoc/), the first student UX organization in the Philippines. For two years, we've had 20+ events with 30+ speakers for over 300 members and 500+ attendees. We've expanded to [California](https://www.facebook.com/profile.php?id=245708449193012) this year.", "I do a bit of writing as well. [Here's an article with a total of 21,000+ views to InVision & Medium](http://blog.invisionapp.com/ux-internship-wisdom/) talking about 50 things I learned spending 3 years as a UX intern.", "I help cultivate the design community in Manila too. I'm the youngest core member of [UX Philippines](https://www.facebook.com/groups/uxphilippines/) and I moderated a panel with some cool people for the [UXPH 2017 Conference](https://www.uxphilippines.com).", 
  ]
    resume = "Resume_Eisenmenger.pdf"

[params.process]
    enable = true
    title = "My Process"
    # subtitle = "Full Process Design"

[params.case_studies]
    enable = false
    title = "Case Studies"
    subtitle = "Selected Works"

[params.footer]
    enable = true
theme = "hugo-lodi-theme"
